### ISSUE TITLE
Tags on GitHub

### ISSUE THREAD

**Issue by dotlambda** [ProtonVPN/python-proton-vpn-killswitch-network-manager#1]
Version 0.0.1 was released on PyPI: https://pypi.org/project/proton-vpn-killswitch-network-manager/#history
However it wasn't tagged on GitHub: https://github.com/ProtonVPN/python-proton-vpn-killswitch-network-manager/tags

**Comment by alexandrevicenzi** [comment]
@calexandru2018 can you fix the tags/releases in this project?

**Comment by calexandru2018** [comment]
Tags have been pushed to all projects and will be getting new tags as we release new versions, thank you all for your patience :)
